# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12.x
      uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: Danger JS Action
      uses: danger/danger-js@9.1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
